version: 2.1

jobs:
  build:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - checkout_build
      - run:
          name: Checkout and Build
          command: |
            cargo --version
            cargo build --verbose
            cargo test --verbose
