version: 2.1


jobs:
  build:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - checkout
      - run: cargo build --verbose
  test:
    docker:
      - image: cimg/rust:1.48.0
    steps:
      - checkout
      - run: cargo test --verbose

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test